algoritmo "entre 100 e 200"
var
   N, S: Inteiro
inicio
   Repita
      Escreva("INFORME UM NÚMERO: ")
      Leia(N)
      Se (N >= 100) e (N <= 200) Entao
         S <- S + 1
      FimSe
   Ate (N = 0)
   LimpaTela
   EscrevaL("#### FIM DO PROGRAMA! ####")
   EscrevaL("LOADING...")
   EscrevaL("LOADING...")
   EscrevaL("LOADING...")
   Escreva("Números entre 100 e 200: ", S)
fimalgoritmo